"""The managed blocks in Waybar's config and stylesheet.

config.jsonc carries // comments, so json.load cannot parse it. Everything here
is text manipulation bounded by the sentinels; a parse-and-reserialise would
destroy the user's comments and formatting. style.css is the same trick with
CSS's comment pair, and the same stance: one region is ours, the rest is not.
"""
import json
import os
import re
import shutil
import subprocess
import tempfile

from . import paths

START = "═══ CCAS — managed block, start ═══"
END = "═══ CCAS — managed block, end ═══"
RULE = "═" * 70

# The account icons live in the centre group. Appending them to modules-right
# put them flush against the screen edge.
HOST_LIST = "modules-center"


def _ccs() -> str:
    """Generated commands carry --gui: Waybar inherits the compositor's stdin,
    which on a TTY session is a real terminal, so stdin sniffing misdetects."""
    return f"{paths.ccs_bin()} --gui"


def module_config(account: dict) -> dict:
    ccs = _ccs()
    return {
        "exec": f"{ccs} render {account['slug']}",
        "interval": 30,
        "signal": account["signal"],
        "tooltip": False,
        # Not a menu-file: Waybar parses that once when the module is built and
        # only a full SIGUSR2 reload re-parses it, so keeping a cached menu
        # fresh meant rebuilding the bar every time a session appeared. This
        # opens the same screen `ccs <slug>` opens in a terminal, generated per
        # click. --gui comes from _ccs(); stdin sniffing cannot be trusted here.
        "on-click": f"{ccs} {account['slug']}",
    }


def placeholder_config() -> dict:
    return {
        "format": f"<span alpha='28000'>{paths.GLYPH}</span>",
        "tooltip": True,
        "tooltip-format": "No Claude accounts configured — click to add one",
        "on-click": f"{_ccs()} manage add",
    }


def visible(reg: dict) -> list:
    """The accounts that get a widget.

    `hidden` is not `removed`: the account keeps its directory, its slug, its
    signal, its usage recording and its chip in the panel — it is off the bar
    and nowhere else. The bar is one surface among several, and an account the
    user rarely switches to is exactly the one they want to stop paying screen
    width for while still being able to reach it.
    """
    return [a for a in reg["accounts"] if not a.get("hidden")]


def module_names(reg: dict):
    if not reg["accounts"]:
        return ["custom/cc-setup"]
    return [f"custom/cc-{a['slug']}" for a in visible(reg)]


def render_block(reg: dict) -> str:
    if reg["accounts"]:
        # Possibly empty, and then the block is its own comments and nothing
        # else. The placeholder is not the answer here: it says "no accounts
        # configured — click to add one", which on a registry holding accounts
        # is a lie, and its click opens a login nobody asked for.
        modules = {f"custom/cc-{a['slug']}": module_config(a) for a in visible(reg)}
    else:
        modules = {"custom/cc-setup": placeholder_config()}
    body = ",\n".join(
        f'    {json.dumps(name)}: {json.dumps(cfg, indent=4, ensure_ascii=False)}'
        for name, cfg in modules.items()
    )
    return (
        f"    // {RULE}\n"
        f"    // {START}\n"
        f"    // Generated by ccs. Do not hand-edit inside this region.\n"
        + (f"{body},\n" if modules else "")
        + f"    // {END}\n"
        f"    // {RULE}\n"
    )


def _strip_text(text: str, comment: str = "//", close: str = "") -> str:
    """Cut out the region between the two rule lines.

    `close` is for CSS, whose comments are a pair rather than a prefix. Bounded
    by the sentinels either way — a parse and reserialise would take the user's
    comments and formatting with it.
    """
    tail = rf"[ \t]*{re.escape(close)}" if close else ""
    fence = rf"^[ \t]*{re.escape(comment)}[ \t]*{re.escape(RULE)}{tail}[ \t]*\n"
    pattern = re.compile(fence + r".*?" + fence, re.DOTALL | re.MULTILINE)
    return pattern.sub("", text)


def _patch_list(text: str, key: str, names) -> str:
    """Replace this key's CCAS entries with `names`, preserving the user's own."""
    def repl(match):
        current = json.loads(match.group(1))
        kept = [n for n in current if not n.startswith("custom/cc-")]
        return f'"{key}": ' + json.dumps(kept + list(names))

    return re.sub(rf'"{re.escape(key)}"\s*:\s*(\[[^\]]*\])', repl, text, count=1)


def _has_list(text: str, key: str) -> bool:
    return re.search(rf'"{re.escape(key)}"\s*:\s*\[', text) is not None


def _insert_empty_list(text: str, key: str) -> str:
    """Add `"<key>": [],` after the opening brace when the config lacks it."""
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("{"):
            lines.insert(i + 1, f'    "{key}": [],\n')
            break
    return "".join(lines)


def _drop_empty_list(text: str, key: str) -> str:
    """Remove `"<key>": [],` once it holds nothing.

    Only ever fires on a list that is empty, and Waybar treats an absent group
    and an empty one identically — so this cannot change how the bar renders.
    It keeps uninstall byte-for-byte on configs that had no centre group.
    """
    return re.sub(rf'^[ \t]*"{re.escape(key)}"\s*:\s*\[\s*\],?[ \t]*\r?\n', "",
                  text, count=1, flags=re.MULTILINE)


def _patch_module_lists(text: str, names) -> str:
    """Put our modules in HOST_LIST and clear them from the other two.

    Clearing the others matters on upgrade: installs that predate a move leave
    entries behind, and a module name Waybar cannot resolve is a config error.
    """
    if names and not _has_list(text, HOST_LIST):
        text = _insert_empty_list(text, HOST_LIST)
    text = _patch_list(text, HOST_LIST, names)
    for other in ("modules-left", "modules-center", "modules-right"):
        if other != HOST_LIST:
            text = _patch_list(text, other, [])
    if not names:
        text = _drop_empty_list(text, HOST_LIST)
    return text


def _atomic_write(path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _backup_once(path) -> None:
    backup = path.with_suffix(path.suffix + ".ccas-orig")
    if not backup.exists():
        shutil.copy2(path, backup)


def render_style_block(reg: dict) -> str:
    """The widgets' spacing and hover, one selector list per rule.

    Generated because it cannot be written once: GTK CSS has no prefix
    matching, so `#custom-cc-*` is not a selector and every slug has to be
    spelled out. Hand-kept, that list went stale the first time an account was
    removed and added back under a new slug — the widget kept working and
    silently stopped answering the pointer, which reads as a broken install.

    No `:active` rule. Waybar's custom module is EventBox-backed and GTK's
    active state is a button concept; measured 2026-07-26, the background under
    a held button stays at the hover value. A rule here would be inert.
    """
    ids = [f"#custom-cc-{a['slug']}" for a in visible(reg)]
    base = ",\n".join(ids)
    hover = ",\n".join(f"{i}:hover" for i in ids)
    return (
        f"/* {RULE} */\n"
        f"/* {START} */\n"
        f"/* Generated by ccs. Do not hand-edit inside this region. */\n"
        f"{base} {{\n"
        f"    padding: 0 9px;\n"
        f"    margin: 0 3px;\n"
        f"    border-radius: 4px;\n"
        f"    transition: background-color 120ms ease;\n"
        f"}}\n"
        f"{hover} {{\n"
        f"    background-color: rgba(255, 255, 255, 0.10);\n"
        f"}}\n"
        f"/* {END} */\n"
        f"/* {RULE} */\n"
    )


def apply(reg: dict) -> None:
    """Both halves of what Waybar reads, together. They are one change: a
    module the stylesheet does not name is a widget that looks and behaves
    unlike its neighbours, which is the shape the drift took."""
    path = paths.waybar_config()
    _backup_once(path)
    text = _strip_text(path.read_text(encoding="utf-8"))
    text = _patch_module_lists(text, module_names(reg))
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("{"):
            lines.insert(i + 1, render_block(reg))
            break
    _atomic_write(path, "".join(lines))
    apply_style(reg)


def apply_style(reg: dict) -> None:
    """Rewrite the managed block at the *end* of style.css.

    Last, not first: equal-specificity CSS is decided by order, and a rule the
    user wrote for a slug that no longer exists — or one written before this
    block existed — must lose to the generated answer rather than fight it.
    Everything above the sentinels stays exactly as it was; CCAS owns this
    region of the file and nothing else in it.
    """
    path = paths.waybar_style()
    if path.exists():
        _backup_once(path)
        text = _strip_text(path.read_text(encoding="utf-8"), "/*", "*/")
    else:
        # Waybar without a stylesheet is unstyled, so there is nothing to
        # preserve and nothing to back up — but the widgets still want their
        # spacing.
        path.parent.mkdir(parents=True, exist_ok=True)
        text = ""
    if visible(reg):
        if text and not text.endswith("\n"):
            text += "\n"
        text += render_style_block(reg)
    _atomic_write(path, text)


def strip(path, comment: str = "//", close: str = "") -> None:
    text = _strip_text(path.read_text(encoding="utf-8"), comment, close)
    if comment == "//":
        text = _patch_module_lists(text, [])
    _atomic_write(path, text)


def reload() -> None:
    """Full bar reload — the only thing that makes Waybar re-read config.jsonc,
    so the set of modules changing is the one thing that still needs it."""
    if os.environ.get("CCAS_NO_RELOAD"):
        return
    subprocess.run(["killall", "-SIGUSR2", "waybar"], check=False,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def signal(n: int) -> None:
    """Flicker-free refresh of one module's label: re-runs `exec`, nothing more."""
    if os.environ.get("CCAS_NO_RELOAD"):
        return
    subprocess.run(["pkill", f"-RTMIN+{n}", "waybar"], check=False,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
