"""Managed blocks in Waybar's config and the user's bashrc.

config.jsonc carries // comments, so json.load cannot parse it. Everything here
is text manipulation bounded by the sentinels; a parse-and-reserialise would
destroy the user's comments and formatting.
"""
import json
import os
import re
import shutil
import subprocess
import tempfile

from . import paths

START = "═══ CCAS — managed block, start ═══"
END = "═══ CCAS — managed block, end ═══"
RULE = "═" * 70

# The account icons live in the centre group. Appending them to modules-right
# put them flush against the screen edge.
HOST_LIST = "modules-center"


def _ccs() -> str:
    """Generated commands carry --gui: Waybar inherits the compositor's stdin,
    which on a TTY session is a real terminal, so stdin sniffing misdetects."""
    return f"{paths.ccs_bin()} --gui"


def module_config(account: dict) -> dict:
    slug = account["slug"]
    ccs = _ccs()
    actions = {
        "new": f"{ccs} launch {slug} new",
        "last": f"{ccs} launch {slug} last",
        "search": f"{ccs} launch {slug} search",
        "hide": f"{ccs} hide {slug} toggle",
        "mng-add": f"{ccs} manage add",
        "mng-rename": f"{ccs} manage rename {slug}",
        "mng-remove": f"{ccs} manage remove {slug}",
    }
    for i in range(paths.HIST_SLOTS):
        actions[f"hist-{i}"] = f"{ccs} launch {slug} hist {i}"
    ids = {"nickname": "disp-nickname", "index": "disp-index",
           "claude code": "disp-cc", "icon only": "disp-icon"}
    for mode in paths.DISPLAY_MODES:
        actions[ids[mode]] = f"{ccs} display {slug} '{mode}'"
    for i in range(len(paths.PALETTE)):
        actions[f"color-{i}"] = f"{ccs} color {slug} {i}"
    return {
        "exec": f"{ccs} render {slug}",
        "interval": 30,
        "signal": account["signal"],
        "tooltip": False,
        "menu": "on-click",
        "menu-file": str(paths.account_dir(slug) / "menu.xml"),
        "menu-actions": actions,
    }


def placeholder_config() -> dict:
    return {
        "format": f"<span alpha='28000'>{paths.GLYPH}</span>",
        "tooltip": True,
        "tooltip-format": "No Claude accounts configured — click to add one",
        "on-click": f"{_ccs()} manage add",
    }


def module_names(reg: dict):
    if not reg["accounts"]:
        return ["custom/cc-setup"]
    return [f"custom/cc-{a['slug']}" for a in reg["accounts"]]


def render_block(reg: dict) -> str:
    if reg["accounts"]:
        modules = {f"custom/cc-{a['slug']}": module_config(a) for a in reg["accounts"]}
    else:
        modules = {"custom/cc-setup": placeholder_config()}
    body = ",\n".join(
        f'    {json.dumps(name)}: {json.dumps(cfg, indent=4, ensure_ascii=False)}'
        for name, cfg in modules.items()
    )
    return (
        f"    // {RULE}\n"
        f"    // {START}\n"
        f"    // Generated by ccs. Do not hand-edit inside this region.\n"
        f"{body},\n"
        f"    // {END}\n"
        f"    // {RULE}\n"
    )


def _strip_text(text: str, comment: str = "//") -> str:
    pattern = re.compile(
        rf"^[ \t]*{re.escape(comment)}[ \t]*{re.escape(RULE)}[ \t]*\n"
        rf".*?"
        rf"^[ \t]*{re.escape(comment)}[ \t]*{re.escape(RULE)}[ \t]*\n",
        re.DOTALL | re.MULTILINE,
    )
    return pattern.sub("", text)


def _patch_list(text: str, key: str, names) -> str:
    """Replace this key's CCAS entries with `names`, preserving the user's own."""
    def repl(match):
        current = json.loads(match.group(1))
        kept = [n for n in current if not n.startswith("custom/cc-")]
        return f'"{key}": ' + json.dumps(kept + list(names))

    return re.sub(rf'"{re.escape(key)}"\s*:\s*(\[[^\]]*\])', repl, text, count=1)


def _has_list(text: str, key: str) -> bool:
    return re.search(rf'"{re.escape(key)}"\s*:\s*\[', text) is not None


def _insert_empty_list(text: str, key: str) -> str:
    """Add `"<key>": [],` after the opening brace when the config lacks it."""
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("{"):
            lines.insert(i + 1, f'    "{key}": [],\n')
            break
    return "".join(lines)


def _drop_empty_list(text: str, key: str) -> str:
    """Remove `"<key>": [],` once it holds nothing.

    Only ever fires on a list that is empty, and Waybar treats an absent group
    and an empty one identically — so this cannot change how the bar renders.
    It keeps uninstall byte-for-byte on configs that had no centre group.
    """
    return re.sub(rf'^[ \t]*"{re.escape(key)}"\s*:\s*\[\s*\],?[ \t]*\r?\n', "",
                  text, count=1, flags=re.MULTILINE)


def _patch_module_lists(text: str, names) -> str:
    """Put our modules in HOST_LIST and clear them from the other two.

    Clearing the others matters on upgrade: installs that predate a move leave
    entries behind, and a module name Waybar cannot resolve is a config error.
    """
    if names and not _has_list(text, HOST_LIST):
        text = _insert_empty_list(text, HOST_LIST)
    text = _patch_list(text, HOST_LIST, names)
    for other in ("modules-left", "modules-center", "modules-right"):
        if other != HOST_LIST:
            text = _patch_list(text, other, [])
    if not names:
        text = _drop_empty_list(text, HOST_LIST)
    return text


def _atomic_write(path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _backup_once(path) -> None:
    backup = path.with_suffix(path.suffix + ".ccas-orig")
    if not backup.exists():
        shutil.copy2(path, backup)


def apply(reg: dict) -> None:
    path = paths.waybar_config()
    _backup_once(path)
    text = _strip_text(path.read_text(encoding="utf-8"))
    text = _patch_module_lists(text, module_names(reg))
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("{"):
            lines.insert(i + 1, render_block(reg))
            break
    _atomic_write(path, "".join(lines))


def strip(path, comment: str = "//") -> None:
    text = _strip_text(path.read_text(encoding="utf-8"), comment)
    if comment == "//":
        text = _patch_module_lists(text, [])
    _atomic_write(path, text)


def bashrc_block() -> str:
    return (
        f"# {RULE}\n"
        f"# {START}\n"
        "claude() {\n"
        '  if [ -n "$CCAS_INNER" ]; then\n'
        '    command claude "$@"\n'
        "  else\n"
        f'    {_ccs()} tty "$@"\n'
        "  fi\n"
        "}\n"
        f"# {END}\n"
        f"# {RULE}\n"
    )


def apply_bashrc() -> None:
    path = paths.bashrc()
    if not path.exists():
        path.write_text("", encoding="utf-8")
    _backup_once(path)
    text = _strip_text(path.read_text(encoding="utf-8"), "#")
    if text and not text.endswith("\n"):
        text += "\n"
    _atomic_write(path, text + bashrc_block())


def reload() -> None:
    """Full bar reload. The only thing that makes Waybar re-parse menu.xml."""
    if os.environ.get("CCAS_NO_RELOAD"):
        return
    subprocess.run(["killall", "-SIGUSR2", "waybar"], check=False,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def signal(n: int) -> None:
    """Flicker-free refresh of one module's label. Does not touch its menu."""
    if os.environ.get("CCAS_NO_RELOAD"):
        return
    subprocess.run(["pkill", f"-RTMIN+{n}", "waybar"], check=False,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
